/**
 * Demo/fallback data — used while Supabase env vars are missing or empty tables.
 * This lets the entire site render locally before any Supabase wiring happens.
 * Once the user runs migrations and seed.sql, this layer disappears automatically.
 */

import type {
  ActivityFeedRow,
  BlogCategoryRow,
  BlogPostRow,
  ClientRow,
  FAQRow,
  PricingTierRow,
  ProcessStepRow,
  ProjectRow,
  ReviewRow,
  ServiceRow,
  SiteSettingsRow,
  SocialLinkRow,
  TeamMemberRow,
  ValueRow,
} from "@/lib/types/database";

const now = new Date().toISOString();

export const demoSiteSettings: SiteSettingsRow = {
  id: 1,
  company_name: "Trellee",
  tagline: "Full-stack digital agency",
  email: "hello@trellee.com",
  city: "Miami, FL",
  whatsapp_url: null,
  calendar_url: null,
  response_time: "Replies within 4 hours, business days",
  hero_eyebrow: "A FULL-STACK DIGITAL AGENCY",
  hero_lede: "agency for teams that ship",
  ticker_words: [
    "websites",
    "brands",
    "CRMs",
    "mobile apps",
    "ad funnels",
    "AI agents",
    "SEO wins",
    "real leads",
  ],
  hero_body:
    "Design, code, and growth — built in one team. From the first commit to the first conversion.",
  hero_cta_label: "Book a call",
  hero_cta_href: "/book",
  stats: [
    { label: "Projects shipped", value: "120", suffix: "+", context: "since 2019" },
    { label: "Client CSAT", value: "4.9", suffix: "/5", context: "across 80+ reviews" },
    { label: "Repeat rate", value: "68", suffix: "%", context: "clients who return" },
    { label: "Open slots / qtr", value: "6", suffix: "", context: "capacity gated, no rush jobs" },
  ],
  booking_quarter: "Q3 2026",
  booking_slots_open: 4,
  cta_heading: "Tell us what you're building.",
  cta_subheading:
    "A 30-minute intro call. No prep needed, no slide deck on our end. Bring the problem, we'll bring the questions.",
  cta_benefits: [
    "No sales script",
    "Same-day scoping notes",
    "Fixed-fee proposal within 72h",
  ],
  newsletter_heading: "The build log, in your inbox.",
  newsletter_subheading:
    "One short note every other week — what we shipped, what broke, what we're reading. No fluff.",
  about_hero_headline: "We build the systems your business runs on.",
  about_hero_subheadline:
    "Trellee is a 12-person studio working across design, engineering, and growth. We treat every project like it's our own product.",
  about_origin_story:
    "Started in 2019 in a Miami coworking space with three founders and one rule: never ship something we wouldn't put our name on.",
  about_philosophy:
    "Speed and craft aren't a tradeoff. They're the same skill — knowing exactly what to skip.",
  contact_intro:
    "Tell us about the project. We read every message and reply within a business day.",
  created_at: now,
  updated_at: now,
};

export const demoServices: ServiceRow[] = [
  {
    id: "svc-crm",
    slug: "custom-crm",
    title: "Custom CRM development",
    short_title: "Custom CRMs",
    icon: "Database",
    category: "Engineering",
    tags: ["Engineering", "AI", "Featured"],
    tile_size: "xl",
    featured: true,
    display_order: 1,
    hero_snippet:
      "Pipeline, dispatch, billing, reporting — built on your stack, owned by you.",
    summary:
      "We design and ship custom CRMs that fit your actual workflow — not the other way around. Built on your stack. Owned by you.",
    problem_statement:
      "Off-the-shelf CRMs force your team to bend to the tool. The tool wins. The team loses 20% of their week to busywork.",
    approach_pillars: [
      {
        title: "Your stack, your rules",
        description:
          "We build on Postgres + your existing auth + your existing storage. No vendor lock-in, no surprise renewals.",
        icon: "Layers",
      },
      {
        title: "Workflow-first design",
        description:
          "We map your real process — including the messy parts — and design the UI around it. Not a generic kanban.",
        icon: "GitBranch",
      },
      {
        title: "Owned, not rented",
        description:
          "Source code lives in your GitHub. You can hire anyone to maintain it. No monthly per-seat fees.",
        icon: "Lock",
      },
    ],
    deliverables: [
      { title: "Discovery doc", description: "End-to-end workflow map + system architecture." },
      { title: "Production CRM", description: "Pipeline, dispatch, contacts, invoicing, reports." },
      { title: "Role-based auth", description: "Owners, dispatchers, technicians, finance — granular." },
      { title: "Mobile app", description: "Field-team companion for status updates + photos." },
      { title: "Integrations", description: "QuickBooks, Stripe, Twilio, Slack — built in." },
      { title: "Docs + Loom walkthroughs", description: "Onboard new staff without a phone call." },
      { title: "30-day post-launch", description: "Bug triage, performance tuning, small adds." },
      { title: "Source code handoff", description: "GitHub repo, CI/CD pipeline, runbook." },
    ],
    hero_code: `import { createClient } from "@/lib/db";

export async function getDealsForOwner(ownerId: string) {
  return db.select()
    .from(deals)
    .where(eq(deals.ownerId, ownerId))
    .orderBy(desc(deals.value));
}`,
    hero_code_lang: "typescript",
    meta_title: "Custom CRM development",
    meta_description:
      "Pipelines, dispatch, invoicing — custom-built on your stack. Owned by you.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-design",
    slug: "design",
    title: "Brand & product design",
    short_title: "Design",
    icon: "PenTool",
    category: "Design",
    tags: ["Brand", "UI"],
    tile_size: "md",
    featured: true,
    display_order: 2,
    hero_snippet: "Brand systems and product surfaces that actually convert.",
    summary:
      "Identity, design systems, marketing sites, product UI. We design like engineers — every pixel ships.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-web",
    slug: "web-development",
    title: "Web development",
    short_title: "Web",
    icon: "Code2",
    category: "Engineering",
    tags: ["Next.js", "Tailwind"],
    tile_size: "md",
    featured: true,
    display_order: 3,
    hero_snippet: "Marketing sites and web apps on a modern stack.",
    summary:
      "Next.js + Tailwind + Postgres. Fast, accessible, server-rendered, deployed to the edge.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-mobile",
    slug: "mobile-apps",
    title: "Mobile apps",
    short_title: "Mobile",
    icon: "Smartphone",
    category: "Engineering",
    tags: ["iOS", "Android"],
    tile_size: "md",
    featured: true,
    display_order: 4,
    hero_snippet: "iOS + Android apps shipped on a shared codebase.",
    summary: "React Native + Expo. One codebase, two stores, native-feeling UX.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-ai",
    slug: "ai-solutions",
    title: "AI solutions",
    short_title: "AI",
    icon: "Sparkles",
    category: "Engineering",
    tags: ["LLMs", "Automation"],
    tile_size: "lg",
    featured: true,
    display_order: 5,
    hero_snippet: "Chatbots, copilots, and LLM-powered automations that pay for themselves.",
    summary:
      "Chatbots, RAG over your docs, internal copilots, agent workflows. We build with Anthropic + OpenAI + open-source models.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-leadgen",
    slug: "lead-generation",
    title: "Lead generation",
    short_title: "Lead gen",
    icon: "Magnet",
    category: "Growth",
    tags: ["Outbound", "Inbound"],
    tile_size: "lg",
    featured: true,
    display_order: 6,
    hero_snippet: "Cold + content + paid working together. Verified leads, not vibes.",
    summary:
      "Cold outbound, content engine, paid funnel — coordinated into one demand machine.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-seo",
    slug: "seo",
    title: "SEO",
    short_title: "SEO",
    icon: "Search",
    category: "Growth",
    tags: ["Technical", "Content"],
    tile_size: "sm",
    featured: false,
    display_order: 7,
    hero_snippet: "Technical SEO + content engine. Rank pages that close deals.",
    summary: "Technical audits + content ops + link building. Programmatic where it fits.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-ads",
    slug: "paid-ads",
    title: "Paid ads",
    short_title: "Paid ads",
    icon: "Target",
    category: "Growth",
    tags: ["Google", "Meta", "LinkedIn"],
    tile_size: "sm",
    featured: false,
    display_order: 8,
    hero_snippet: "Google, Meta, LinkedIn. Creative + targeting + landing pages.",
    summary: "Creative + targeting + landing pages — managed as one system.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-marketing",
    slug: "marketing",
    title: "Marketing strategy",
    short_title: "Marketing",
    icon: "Megaphone",
    category: "Growth",
    tags: ["Strategy", "Content"],
    tile_size: "sm",
    featured: false,
    display_order: 9,
    hero_snippet: "Positioning, messaging, content engine that compounds.",
    summary:
      "Positioning, messaging hierarchy, content engine. The boring stuff that compounds.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-scraping",
    slug: "web-scraping",
    title: "Web scraping",
    short_title: "Scraping",
    icon: "ScanLine",
    category: "Engineering",
    tags: ["Data"],
    tile_size: "sm",
    featured: false,
    display_order: 10,
    hero_snippet: "Data extraction at scale. Compliant, resilient, scheduled.",
    summary:
      "Data extraction at scale — compliant, resilient, scheduled. Delivered as APIs or feeds.",
    problem_statement: null,
    approach_pillars: [],
    deliverables: [],
    hero_code: null,
    hero_code_lang: "typescript",
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
];

export const demoPricingTiers: PricingTierRow[] = [
  {
    id: "tier-mvp",
    service_id: "svc-crm",
    name: "MVP",
    price: "$18k",
    price_suffix: "/project",
    description: "One core workflow, 3-5 user roles, single integration. Live in ~6 weeks.",
    features: [
      "Discovery + architecture doc",
      "1 core workflow (e.g. pipeline + dispatch)",
      "Role-based auth (3-5 roles)",
      "1 external integration",
      "Mobile-responsive web app",
      "30-day post-launch support",
    ],
    highlighted: false,
    cta_label: "Book a call",
    cta_href: "/book",
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "tier-pro",
    service_id: "svc-crm",
    name: "Production",
    price: "$36k",
    price_suffix: "/project",
    description: "Full CRM with multiple workflows, integrations, and a native mobile app. ~10 weeks.",
    features: [
      "Everything in MVP",
      "Multiple workflows (sales + ops + finance)",
      "Native mobile app (iOS + Android)",
      "3-4 external integrations",
      "Reporting + dashboards",
      "90-day post-launch support",
      "Loom + written docs",
    ],
    highlighted: true,
    cta_label: "Book a call",
    cta_href: "/book",
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "tier-scale",
    service_id: "svc-crm",
    name: "Scale",
    price: "Custom",
    price_suffix: "",
    description: "Multi-entity, multi-region, white-labeled, or with embedded AI. We scope to fit.",
    features: [
      "Everything in Production",
      "Multi-tenant architecture",
      "Embedded AI / RAG over your data",
      "Custom SLAs",
      "Dedicated engineering retainer",
      "Quarterly architecture reviews",
    ],
    highlighted: false,
    cta_label: "Talk to founders",
    cta_href: "/contact",
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
];

export const demoFAQs: FAQRow[] = [
  {
    id: "faq-1",
    question: "How long does a typical CRM project take?",
    answer:
      "MVP: ~6 weeks. Production: ~10 weeks. We share weekly demos so you see progress in real time, not at the end.",
    category: "custom-crm",
    service_id: "svc-crm",
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "faq-2",
    question: "Do we own the code when you're done?",
    answer:
      "Yes — the GitHub repo, CI/CD pipeline, and infrastructure-as-code all transfer to your org. No license, no per-seat fees.",
    category: "custom-crm",
    service_id: "svc-crm",
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "faq-3",
    question: "Can you integrate with our existing tools?",
    answer:
      "Yes. We commonly integrate with QuickBooks, Stripe, Twilio, Slack, Google Workspace, Salesforce, and HubSpot. If it has an API, we can talk to it.",
    category: "custom-crm",
    service_id: "svc-crm",
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "faq-4",
    question: "What if we need changes after launch?",
    answer:
      "30 days of bug triage + small adds are included. After that, we offer monthly retainers or pay-per-sprint engagements.",
    category: "custom-crm",
    service_id: "svc-crm",
    display_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "faq-5",
    question: "Who do we work with day-to-day?",
    answer:
      "A 2-3 person pod: one engineer-lead, one designer, one growth lead if relevant. Same team, start to finish.",
    category: "general",
    service_id: null,
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "faq-6",
    question: "How do you price projects?",
    answer:
      "Fixed-fee for defined scope. Hourly only for explicit exploration sprints. No hidden costs, no \"discovery phases\" that mysteriously inflate.",
    category: "general",
    service_id: null,
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
];

export const demoClients: ClientRow[] = [
  { id: "c1", name: "Northside", logo_url: null, website_url: null, featured: true, display_order: 1, created_at: now, updated_at: now },
  { id: "c2", name: "Reef Capital", logo_url: null, website_url: null, featured: true, display_order: 2, created_at: now, updated_at: now },
  { id: "c3", name: "Otis Health", logo_url: null, website_url: null, featured: true, display_order: 3, created_at: now, updated_at: now },
  { id: "c4", name: "Helio", logo_url: null, website_url: null, featured: true, display_order: 4, created_at: now, updated_at: now },
  { id: "c5", name: "Bayline", logo_url: null, website_url: null, featured: true, display_order: 5, created_at: now, updated_at: now },
  { id: "c6", name: "Forge & Co", logo_url: null, website_url: null, featured: true, display_order: 6, created_at: now, updated_at: now },
  { id: "c7", name: "Quay", logo_url: null, website_url: null, featured: true, display_order: 7, created_at: now, updated_at: now },
  { id: "c8", name: "Sunbreak", logo_url: null, website_url: null, featured: true, display_order: 8, created_at: now, updated_at: now },
];

export const demoProjects: ProjectRow[] = [
  {
    id: "p-northside",
    slug: "northside-operator",
    title: "Northside Operator",
    client_name: "Northside HVAC",
    client_id: null,
    summary:
      "A custom CRM + dispatch system that replaced 4 SaaS tools and cut admin time by 47%.",
    hero_eyebrow: "CASE STUDY · Q4 2025",
    brief:
      "Northside, a 40-person residential HVAC operator, was running their business across Jobber, QuickBooks, Google Sheets, and WhatsApp. Admin staff spent 3 hours a day reconciling status across systems. They asked us to consolidate.",
    approach:
      "We mapped the dispatch-to-invoice flow end-to-end with their ops manager over two weeks, then built a single CRM with pipeline, dispatch, technician mobile app, and Stripe + QuickBooks sync.",
    outcome:
      "Admin time dropped from 15 hrs/week to 8 hrs/week. Average days-to-invoice fell from 12 to 3. Field techs adopted the mobile app within a week (no training calls).",
    cover_url: null,
    thumbnail_url: null,
    gallery: [],
    metrics: [
      { label: "Admin time", value: "−47%", context: "vs. previous tool stack" },
      { label: "Days to invoice", value: "12 → 3", context: "75% faster cash collection" },
      { label: "Tools replaced", value: "4", context: "Jobber, QB, Sheets, WhatsApp" },
      { label: "Tech adoption", value: "100%", context: "within first week" },
    ],
    technologies: [
      { name: "Next.js", category: "Frontend" },
      { name: "Postgres", category: "Database" },
      { name: "Tailwind", category: "Frontend" },
      { name: "Stripe", category: "Payments" },
      { name: "Expo", category: "Mobile" },
      { name: "Twilio", category: "Comms" },
      { name: "QuickBooks API", category: "Integration" },
      { name: "Vercel", category: "Infra" },
    ],
    service_categories: ["custom-crm", "mobile-apps", "web-development"],
    featured: true,
    featured_order: 1,
    status: "published",
    published_at: now,
    meta_title: "Northside Operator — Case Study",
    meta_description:
      "How we replaced 4 SaaS tools with one custom CRM and cut admin time by 47%.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-reef",
    slug: "reef-capital-funnel",
    title: "Reef Capital — paid funnel",
    client_name: "Reef Capital",
    client_id: null,
    summary:
      "A paid + landing-page system that 3× qualified leads at a lower CPL.",
    hero_eyebrow: "CASE STUDY · Q3 2025",
    brief:
      "A boutique RIA firm wanted to scale qualified consultations without raising creative budget 3×.",
    approach:
      "Audience research → 8 landing-page variants → Meta + Google paid mix → CRM scoring.",
    outcome:
      "+212% qualified leads MoM at 52% lower CPL. ROAS 4.8×.",
    cover_url: null,
    thumbnail_url: null,
    gallery: [],
    metrics: [
      { label: "Leads", value: "+212%", context: "MoM" },
      { label: "CPL", value: "−52%", context: "" },
      { label: "ROAS", value: "4.8×", context: "" },
    ],
    technologies: [
      { name: "Meta Ads", category: "Paid" },
      { name: "Google Ads", category: "Paid" },
      { name: "Webflow", category: "Frontend" },
    ],
    service_categories: ["paid-ads", "lead-generation"],
    featured: true,
    featured_order: 2,
    status: "published",
    published_at: now,
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-otis",
    slug: "otis-health-app",
    title: "Otis Health — patient app",
    client_name: "Otis Health",
    client_id: null,
    summary:
      "Native iOS/Android app for chronic-care patients to track medication, appointments, and labs.",
    hero_eyebrow: "CASE STUDY · Q2 2025",
    brief: "Otis needed a patient-facing app to drive adherence on chronic care plans.",
    approach: "Discovery with patients + care team → Expo app → backend → pilot with 200 patients.",
    outcome:
      "Medication adherence up 28%. App store rating 4.8★ across 200+ reviews.",
    cover_url: null,
    thumbnail_url: null,
    gallery: [],
    metrics: [
      { label: "Adherence", value: "+28%", context: "vs. baseline" },
      { label: "App rating", value: "4.8★", context: "200+ reviews" },
    ],
    technologies: [
      { name: "Expo", category: "Mobile" },
      { name: "React Native", category: "Mobile" },
      { name: "Postgres", category: "Database" },
    ],
    service_categories: ["mobile-apps", "design"],
    featured: true,
    featured_order: 3,
    status: "published",
    published_at: now,
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
];

export const demoReviews: ReviewRow[] = [
  {
    id: "r-1",
    type: "text",
    author_name: "Maya Chen",
    author_role: "COO",
    author_company: "Northside HVAC",
    author_avatar_url: null,
    quote:
      "We replaced four tools with one CRM. Our dispatchers stopped doing reconciliation work overnight. The team didn't even need a training call — they just used it.",
    rating: 5,
    video_url: null,
    video_thumbnail_url: null,
    duration: null,
    project_id: "p-northside",
    featured: true,
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "r-2",
    type: "video",
    author_name: "Daniel Park",
    author_role: "Founder",
    author_company: "Reef Capital",
    author_avatar_url: null,
    quote: null,
    rating: 5,
    video_url: null,
    video_thumbnail_url: null,
    duration: "1:24",
    project_id: "p-reef",
    featured: true,
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "r-3",
    type: "video",
    author_name: "Priya Shah",
    author_role: "Head of Product",
    author_company: "Otis Health",
    author_avatar_url: null,
    quote: null,
    rating: 5,
    video_url: null,
    video_thumbnail_url: null,
    duration: "2:08",
    project_id: "p-otis",
    featured: true,
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "r-4",
    type: "text",
    author_name: "James Whitlock",
    author_role: "CEO",
    author_company: "Helio Solar",
    author_avatar_url: null,
    quote:
      "The clearest scope, the cleanest delivery, and the only agency that didn't try to sell us a retainer we didn't need.",
    rating: 5,
    video_url: null,
    video_thumbnail_url: null,
    duration: null,
    project_id: null,
    featured: true,
    display_order: 4,
    created_at: now,
    updated_at: now,
  },
];

export const demoProcessSteps: ProcessStepRow[] = [
  {
    id: "ps-1",
    step_number: "01",
    phase_label: "DISCOVERY",
    title: "Map the real workflow",
    description:
      "Two-week immersion with the team that'll actually use the system. We don't trust org charts; we watch the work.",
    duration: "Week 1-2",
    service_id: null,
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ps-2",
    step_number: "02",
    phase_label: "ARCHITECTURE",
    title: "Design the system",
    description:
      "Data model, role hierarchy, integration map. You see the doc before any code is written.",
    duration: "Week 2",
    service_id: null,
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ps-3",
    step_number: "03",
    phase_label: "BUILD",
    title: "Ship weekly demos",
    description:
      "Every Friday, you see a working slice in staging. No big-bang reveals, no surprises at the end.",
    duration: "Week 3-8",
    service_id: null,
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ps-4",
    step_number: "04",
    phase_label: "PILOT",
    title: "Launch to a real subset",
    description:
      "Two-week pilot with your power users. Fix the rough edges before the whole team touches it.",
    duration: "Week 9",
    service_id: null,
    display_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ps-5",
    step_number: "05",
    phase_label: "HANDOFF",
    title: "Hand over the keys",
    description:
      "Repo, runbook, Loom walkthroughs. 30 days of post-launch support. You own it from day one.",
    duration: "Week 10",
    service_id: null,
    display_order: 5,
    created_at: now,
    updated_at: now,
  },
];

export const demoValues: ValueRow[] = [
  {
    id: "v-1",
    title: "Ship weekly",
    description:
      "A Friday demo every week. No surprises at the end of a project.",
    icon: "Rocket",
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "v-2",
    title: "Write things down",
    description:
      "Decisions, tradeoffs, architecture — all in writing, all sharable. Verbal-only doesn't scale.",
    icon: "FileText",
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "v-3",
    title: "Fixed-fee, fixed-scope",
    description:
      "We scope it, we price it, we deliver it. Hourly is for explorations only.",
    icon: "FileSignature",
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "v-4",
    title: "Own the outcome",
    description:
      "If it ships and doesn't work, that's our problem to fix — not yours.",
    icon: "Target",
    display_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "v-5",
    title: "Boring stack wins",
    description:
      "We use what we trust: Postgres, Next.js, Tailwind. Novelty for its own sake costs you.",
    icon: "Layers",
    display_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "v-6",
    title: "Hire slowly",
    description:
      "Twelve people on staff, and that number grows when the work — not the hype — demands it.",
    icon: "Users",
    display_order: 6,
    created_at: now,
    updated_at: now,
  },
];

export const demoTeam: TeamMemberRow[] = [
  {
    id: "t-1",
    name: "Camila Rivera",
    role: "Founder · Engineering",
    bio: "Built systems for HVAC, healthcare, and fintech. Eight years writing software that survives Monday morning.",
    avatar_url: null,
    links: [],
    display_order: 1,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-2",
    name: "Marco Aldama",
    role: "Founder · Design",
    bio: "Ex-IDEO and indie studios. Designs that ship the same week they're approved.",
    avatar_url: null,
    links: [],
    display_order: 2,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-3",
    name: "Priya Mehta",
    role: "Founder · Growth",
    bio: "Ran growth at two Series B startups. Cares about the metric that pays salaries.",
    avatar_url: null,
    links: [],
    display_order: 3,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-4",
    name: "Jordan Reyes",
    role: "Senior Engineer",
    bio: "Backend & infra. Has opinions about Postgres indexes and is right.",
    avatar_url: null,
    links: [],
    display_order: 4,
    active: true,
    created_at: now,
    updated_at: now,
  },
];

export const demoActivity: ActivityFeedRow[] = [
  {
    id: "a-1",
    message: "Shipped Northside dispatch v2.4",
    badge: "deploy",
    href: null,
    occurred_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    created_at: now,
  },
  {
    id: "a-2",
    message: "Reef Capital — funnel CPL down to $84",
    badge: "growth",
    href: null,
    occurred_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    created_at: now,
  },
  {
    id: "a-3",
    message: "Otis Health app submitted to App Store",
    badge: "milestone",
    href: null,
    occurred_at: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    created_at: now,
  },
  {
    id: "a-4",
    message: "New case study published: Northside Operator",
    badge: "post",
    href: "/portfolio/northside-operator",
    occurred_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    created_at: now,
  },
  {
    id: "a-5",
    message: "Helio Solar — landing page v3 live",
    badge: "deploy",
    href: null,
    occurred_at: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
    created_at: now,
  },
];

export const demoSocialLinks: SocialLinkRow[] = [
  { id: "s-x", platform: "x", url: "https://x.com/trellee", display_order: 1, created_at: now },
  { id: "s-li", platform: "linkedin", url: "https://linkedin.com/company/trellee", display_order: 2, created_at: now },
  { id: "s-gh", platform: "github", url: "https://github.com/trellee", display_order: 3, created_at: now },
];

export const demoBlogCategories: BlogCategoryRow[] = [
  { id: "bc-eng", slug: "engineering", name: "Engineering", description: "Code, architecture, and how things actually work.", display_order: 1, created_at: now, updated_at: now },
  { id: "bc-design", slug: "design", name: "Design", description: "Design system thinking, type, motion.", display_order: 2, created_at: now, updated_at: now },
  { id: "bc-growth", slug: "growth", name: "Growth", description: "Acquisition, retention, paid + content.", display_order: 3, created_at: now, updated_at: now },
  { id: "bc-process", slug: "process", name: "Process", description: "How we run projects. The honest version.", display_order: 4, created_at: now, updated_at: now },
];

export const demoBlogPosts: BlogPostRow[] = [
  {
    id: "bp-1",
    slug: "why-we-dont-do-discovery-phases",
    title: "Why we don't do discovery phases",
    excerpt:
      "The dirty secret of discovery phases: they're how agencies extend the contract without committing to scope. Here's what we do instead.",
    body: "## We don't do discovery phases\n\nDiscovery phases are how agencies turn a 4-week project into 12 weeks without committing to deliverables...",
    cover_url: null,
    category_id: "bc-process",
    author_id: "t-1",
    reading_time: 6,
    featured: true,
    status: "published",
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bp-2",
    slug: "the-only-saas-metric-that-pays-salaries",
    title: "The only SaaS metric that pays salaries",
    excerpt:
      "Vanity metrics are loud. The one number that actually pays your team is quieter — and most dashboards bury it.",
    body: "## The one number\n\n...",
    cover_url: null,
    category_id: "bc-growth",
    author_id: "t-3",
    reading_time: 4,
    featured: false,
    status: "published",
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bp-3",
    slug: "designing-for-the-monday-morning-test",
    title: "Designing for the Monday morning test",
    excerpt:
      "If the dispatcher can't use it at 7am with coffee in one hand, it doesn't matter how beautiful it is on Dribbble.",
    body: "## Monday morning\n\n...",
    cover_url: null,
    category_id: "bc-design",
    author_id: "t-2",
    reading_time: 5,
    featured: false,
    status: "published",
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString(),
    meta_title: null,
    meta_description: null,
    created_at: now,
    updated_at: now,
  },
];
